DEVELOPER.md

[GitHub markdown alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) require the alert type to be on their own line for the alert to properly render.
Fixing broken rendering:

chore: update rendering of tip alert in DEVELOPER.md

---

src/toolbox_langchain/utils.py
tests/test_utils.py

Temporarily relaxes type checking in the toolbox manifest handling. Currently, the toolbox manifest does not include `items` information (along with the `type` field) in the `parameters` field of the manifest. This change allows lists containing any type of value (except nested lists) as a workaround. This will be reverted once the toolbox manifest provides type information.
> [!NOTE]
> This is a temporary fix. It allows tools relying on the manifest to function until the toolbox's manifest includes type information.

fix: Fix issue occurring when using a tool with list with type

---

.github/sync-repo-settings.yaml

This is to match with what the current set of enabled presubmit checks are in this repo. Currently we do not have the sync settings bot enabled in this repo, so we are manually setting this up in the repo settings through Github UI.

chore: Add additional presubmit checks in sync-repo-settings.

---

README.md

Remove the temporary instructions of installing the package locally now that the SDK is available as a PyPI package.
Also move the installation instructions before the quickstart sections since installation is required before quickstart code can work.

doc: Update README installation instructions

---

src/toolbox_langchain/utils.py
tests/conftest.py
tests/test_utils.py

Fix issue with array parameter type throwing an error `generic::invalid_argument: Unable to submit request because search_airports functionDeclaration parameters.airlines schema didn't specify the schema type field.`
This PR does the following:
* Parse items from manifest to `ParameterSchema`.
* Convert item typing to specific type instead of using `Union`.

fix: add items to parameter schema

---

src/toolbox_langchain/utils.py
tests/test_utils.py

Earlier we made all fields as optional since we wanted to keep some fields optional for the LLM. Since Toolbox did not support optional fields, there was no way to know which fields were optional, so as a worst-case, we did a temporary workaround of keeping all fields as optional in the schema generated by Toolbox SDK.
Now, there has been some evidence that the LLMs do not work very well with optional parameters, and so we have decided not to support optional fields for now, neither in Toolbox service nor in the SDK.
This PR removes that temporary fix of making all the fields optional.
This PR also removes an augmentation to the request body where `None` values were converted to empty strings (`''`). This is because now that LLM knows no fields are optional, we can be sure that we would …

fix: Make all fields required in Tool schema

---

tests/conftest.py

This PR adds support for testing on both development (dev) and released (numbered) versions of the toolbox.
When testing against a `dev` version, the toolbox code is compiled directly from the repository, ensuring the latest changes are included. SDK tests are then executed against this newly compiled binary.
This is based on https://github.com/googleapis/genai-toolbox/pull/165

tests(sdk): Run tests on toolbox dev version

---

.github/workflows/schedule_reporter.yml

Similar to https://github.com/googleapis/genai-toolbox-llamaindex-python/pull/32

chore: Update GHA workflow permissions for Cloud Build Reporter

---

src/toolbox_langchain/async_tools.py
src/toolbox_langchain/utils.py

This is to prevent tool invocation if the required tool-level auth is missing. This is similar to how we prevent tool invocation if a parameter-level auth is missing.

feat: Add support for checking tool-level auth before tool invocation.

---

.github/release-trigger.yml

As per the [Kokoro release script migration](https://docs.google.com/document/d/1P0Z5FXWd9BbyeYDUbWzYb6rbGppmvGSbM8p8YBFW-Mo/edit?tab=t.0#heading=h.2ivc9rkl4kzo), we now use multi_scm for releases.

chore: use multiScm for Kokoro release builds

---

README.md

tool name is required in `load_tool` function.

docs: update syntax error on readme

---

release-please-config.json

Creates better looking release PRs. The components are mentioned as a part of the release PR.
`include-component-in-tag` is true by default, so we can omit the config.

chore: change config component

---

packages/toolbox-core/pyproject.toml
packages/toolbox-core/src/toolbox_core/client.py
packages/toolbox-core/src/toolbox_core/tool.py
packages/toolbox-core/tests/test_client.py

Add's support for specifying token getters for use with [Auth Service features](https://googleapis.github.io/genai-toolbox/resources/authservices/#specifying-id-tokens-from-clients).
* ToolboxClient: adds optional `auth_token_getters` argument to the `load_tool` and `load_toolset` functions
* ToolboxTool: adds `add_auth_token_getters` function to `ToolboxTool`

feat(toolbox-core): add authenticated parameters support

---

packages/toolbox-core/src/toolbox_core/client.py
packages/toolbox-core/src/toolbox_core/tool.py
packages/toolbox-core/tests/test_client.py

Adds basic support for "bound parameters", which is a client-side only feature that allow you to bind the value of a parameter to a value (or function that produces a value). 
Makes the following changes:
* ToollboxClient: `load_tool` and `load_toolset` now have an optional parameter `bound_params`
* ToolboxTool: adds `bind_parameters` method

feat(toolbox-core): add support for bound parameters

---

packages/toolbox-core/src/toolbox_core/version.py

We want to create a 0.1.0 release for toolbox-core.
We need to have the current version as less than 0.1.0, so that the new version can be 0.1.0

chore: change back version to allow releases

---

release-please-config.json

Currently, our release tag looks like: `toolbox-core: v0.1.0`.
`Release-please` searches for previously tagged releases and creates new releases following that. Currently, it was searching for `toolbox-core: 0.1.0`, and thus unable to fetch the previous releases. Here, we include a `v` in the release tag search.
Note: I have updated the release tag for `toolbox-langchain` to `toolbox-langchain: v0.1.0` from `v0.1.0`.

fix: correct tagging of releases

---

.github/release-please.yml

The release please automated releases look like [this](https://github.com/googleapis/genai-toolbox-langchain-python/pull/151) because they're not using [Manifest Driven Release](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md).
Adding this to the release file allows `release-please` to read the existing [manifest](https://github.com/googleapis/genai-toolbox-langchain-python/blob/main/.release-please-manifest.json) and [config](https://github.com/googleapis/genai-toolbox-langchain-python/blob/main/release-please-config.json) files and create releases accordingly.

chore: use manifest file to create releases

---

packages/toolbox-core/src/toolbox_core/tool.py
packages/toolbox-core/tests/test_e2e.py
packages/toolbox-core/tests/test_tools.py

Previously we were only supporting sync token getters. Adding support for async getters could be beneficial performance-wise.

feat: Add support for async token getters to ToolboxTool

---

packages/toolbox-core/pyproject.toml
packages/toolbox-core/src/toolbox_core/client.py
packages/toolbox-core/src/toolbox_core/sync_client.py
packages/toolbox-core/src/toolbox_core/tool.py
packages/toolbox-core/tests/test_client.py
packages/toolbox-core/tests/test_e2e.py
packages/toolbox-core/tests/test_protocol.py
packages/toolbox-core/tests/test_tools.py

```
Name                              Stmts   Miss  Cover
-----------------------------------------------------
src/toolbox_core/__init__.py          3      0   100%
src/toolbox_core/client.py           50      0   100%
src/toolbox_core/protocol.py         32      0   100%
src/toolbox_core/tool.py             93      0   100%
```
This PR also adds a test dependency of `pytest-cov`.
> [!NOTE]
> Unit test case coverage for sync counterparts will be added in a future PR.

chore: Add unit tests for the tool, client and protocol files

---

packages/toolbox-langchain/README.md
packages/toolbox-langchain/src/toolbox_langchain/async_client.py
packages/toolbox-langchain/src/toolbox_langchain/async_tools.py
packages/toolbox-langchain/src/toolbox_langchain/client.py
packages/toolbox-langchain/src/toolbox_langchain/tools.py
packages/toolbox-langchain/tests/test_async_client.py
packages/toolbox-langchain/tests/test_async_tools.py
packages/toolbox-langchain/tests/test_client.py
packages/toolbox-langchain/tests/test_e2e.py
packages/toolbox-langchain/tests/test_tools.py

* In the `load_tool` and `load_toolset` methods (and their async counterparts `aload_tool`, `aload_toolset`) within the `toolbox-langchain` package, rename the `auth_tokens` parameter to `auth_token_getters`.
* Deprecate the old `auth_tokens` parameter.
This is to align with the `toolbox-core` APIs and also because the suffix of `_getter(s)` make these APIs more descriptive and accurate.
Because of the `_getter` suggesting it should be a function rather than a value, it actively encourages best practices regarding token security and lifecycle management (like refresh logic), which is crucial for production systems.

chore(toolbox-langchain): rename auth_tokens to auth_token_getters

---

packages/toolbox-core/src/toolbox_core/tool.py
packages/toolbox-core/tests/test_client.py

This pull request updates the `bind_parameters` helper function within the `ToolboxTool` of the `toolbox-core` package to enhance parameter binding management.
* The helper now throws an explicit error if a user attempts to bind a parameter that has already been bound. This change aims to prevent unexpected behavior and improve the clarity of parameter assignments.
* The error that previously occurred when a user tried to bind a parameter not present in the tool's schema has been removed. This validation will be handled by a `strict` mode implementation in a future PR.

fix(toolbox-core): Prevent rebinding of parameters in ToolboxTool

---

packages/toolbox-core/src/toolbox_core/client.py
packages/toolbox-core/src/toolbox_core/tool.py

This PR refactors `__parse_tool` to accurately determine and return the `used_auth_keys` value.
Investigation revealed that the previously incorrect value was not referenced elsewhere, meaning this bug did not manifest as an active issue. However, this correction enhances the reliability of `__parse_tool` for any future use cases.
> [!NOTE]
> Unit tests for the underlying helper function that identifies these used auth keys, including tests for the correct values, had already been added in #203. As this PR's change corrects a value that wasn't actively tested or used, no unit test modifications are needed here.

fix: Ensure `__parse_tool` returns correct `used_auth_keys`

---

packages/toolbox-core/src/toolbox_core/client.py
packages/toolbox-core/src/toolbox_core/tool.py
packages/toolbox-core/tests/test_client.py
packages/toolbox-core/tests/test_e2e.py
packages/toolbox-core/tests/test_sync_e2e.py

This pull request introduces a `strict` mode to the `load_toolset` method and refines the validation behavior of the `load_tool` method.
* Ensures tools are configured as intended and are using all provided authentication mechanisms and parameters.
* Helps identify misconfigurations or unused inputs during the tool loading phase, rather than leading to potential runtime issues.
* Makes it explicit when a tool is not interacting with expected configurations.
The `load_toolset` method now includes an optional `strict` flag:
* `strict = False` (Default Behavior):
* Validation will fail (raising a `ValueError`) if at least one authentication token getter (from the `auth_token_getters` provided) or at least one bound parameter (from the `bound_params` provided) is not utilized by any of the …

feat: Implement strict validation for client while loading tools

---

packages/toolbox-core/README.md
packages/toolbox-core/src/toolbox_core/sync_tool.py
packages/toolbox-core/src/toolbox_core/tool.py
packages/toolbox-core/tests/test_client.py
packages/toolbox-core/tests/test_e2e.py
packages/toolbox-core/tests/test_sync_e2e.py

This aligns with the other orchestration package naming, and is more precise and convenient.
`bind_parameters()` --> `bind_params()`
```py
bound_tool = tool.bind_parameters({"param": "value"})
```
```py
bound_tool = tool.bind_params({"param": "value"})
```

feat(toolbox-core)!: Align toolbox core's bind params API with orchestration packages

---

packages/toolbox-core/src/toolbox_core/tool.py
packages/toolbox-core/tests/test_client.py

Post adding the feature of adding client-level auth headers (#178), we have the logic for creating an auth header, from the given auth token getter name, in 3 different places.
This PR unifies all of that logic into a single helper to improve maintenance, and make it easier to change the way we add suffix/prefix, and reduces WET code.

chore(toolbox-core): Consolidate auth header creation logic

---

packages/toolbox-core/src/toolbox_core/tool.py
packages/toolbox-core/tests/test_client.py
packages/toolbox-core/tests/test_tool.py

Previously, the `ToolboxTool.add_auth_token_getters` method only validated against existing registered getters or conflicts with client headers. It did not verify if *all* the auth token getters provided were actually used or required by the specific tool instance they were being added to.
This PR enhances the validation in `add_auth_token_getters`. It now leverages the `used_auth_token_getters` information returned by the existing `identify_required_authn_params` call. This allows the method to confirm that every getter passed in is genuinely required by the tool, raising an error if any are unused.
This ensures that only relevant auth token getters are attempted to be registered for a tool, preventing misconfigurations and human errors.
> [!NOTE]
> This validation aligns with the …

fix: Add validation to ensure added auth token getters are used by the tool

---

packages/toolbox-core/src/toolbox_core/tool.py
packages/toolbox-core/tests/test_client.py
packages/toolbox-core/tests/test_tool.py

This change introduces a warning that is displayed immediately before a tool invocation if:
1. The invocation includes an authentication header.
2. The connection is being made over non-secure HTTP.
> [!IMPORTANT]
The purpose of this warning is to alert the user to the security risk of sending credentials over an unencrypted channel and to encourage the use of HTTPS.

feat: Warn on insecure tool invocation with authentication

---

packages/toolbox-core/src/toolbox_core/sync_client.py
packages/toolbox-core/src/toolbox_core/tool.py
packages/toolbox-core/tests/test_client.py

Also remove an unused `type: ignore` comment.

fix: Fix issue causing masking of empty loop or thread check while loading tool/toolset

---

packages/toolbox-core/tests/test_sync_client.py

chore: Simplify sync_client fixture

---

packages/toolbox-core/src/toolbox_core/client.py
packages/toolbox-core/src/toolbox_core/sync_client.py
packages/toolbox-core/src/toolbox_core/tool.py
packages/toolbox-core/tests/test_client.py
packages/toolbox-core/tests/test_sync_client.py

Now we do not need to put an `await` while calling `add_headers()` method.
```py
await client.add_headers({"header": "value"})
```
```py
client.add_headers({"header": "value"})
```

fix(toolbox-core)!: Simplify add_headers to make it sync in async client

---

packages/toolbox-core/src/toolbox_core/tool.py
packages/toolbox-core/tests/test_client.py
packages/toolbox-core/tests/test_e2e.py
packages/toolbox-core/tests/test_sync_client.py
packages/toolbox-core/tests/test_sync_e2e.py

Earlier a `ValueError` was being thrown. In case of unauthenticated tool calls, a `PermissionError` is more suitable.

fix(toolbox-core)!: Throw PermissionError on unauthenticated tool invocation

---

packages/toolbox-core/src/toolbox_core/sync_client.py

This aligns with the async client's `load_toolset` method.

feat: Make name optional while loading toolset through sync client

---

packages/toolbox-langchain/src/toolbox_langchain/async_client.py

This PR addresses the scenario where a user provides both `auth_tokens` and `auth_headers`, both of which are deprecated arguments.
Previously, if a user provided both `auth_tokens` and `auth_headers`, the authentication tokens from `auth_headers` were prioritized. This created an inconsistent behavior, especially considering that `auth_tokens` was deprecated more recently than `auth_headers`.
This change shifts the precedence to `auth_tokens`. Now, if both `auth_tokens` and `auth_headers` are present, only the authentication tokens specified in `auth_tokens` will be considered.
1.  `auth_tokens` was deprecated more recently than `auth_headers`. Prioritizing the more recently deprecated argument provides a clearer signal to users about the intended deprecation path and guides them towards …

chore: Define precedence for deprecated 'auth_tokens' vs. 'auth_headers'

---

packages/toolbox-langchain/pyproject.toml

We would tie up the versions of orchestration specific packages (`toolbox-langchain` in this case), so that they are always equal.

chore(toolbox-langchain): Pin toolbox-core version

---

packages/toolbox-core/README.md
packages/toolbox-core/src/toolbox_core/sync_tool.py
packages/toolbox-core/src/toolbox_core/tool.py
packages/toolbox-core/tests/test_sync_tool.py
packages/toolbox-core/tests/test_tool.py

This brings it on par with the existing singular method of `bind_param` corresponding to the `bind_params` method.

feat: Add convenience methods for adding single auth token getter to tools

---

packages/toolbox-langchain/pyproject.toml
packages/toolbox-llamaindex/pyproject.toml

To ensure `toolbox-core`, `toolbox-langchain`, and `toolbox-llamaindex` are always released together with the exact same version, this PR pins the `toolbox-core` dependency in the `pyproject.toml` files of `toolbox-langchain` and `toolbox-llamaindex` to match their own versions.
This allows `release-please` to automatically update this pinned dependency when bumping package versions.
> [!NOTE]
> This change does not affect `requirements.txt` files, as they handle local editable installs of `toolbox-core` which do not require explicit versioning.

chore: Align `toolbox-core` dependency for synchronized releases

---

packages/toolbox-core/src/toolbox_core/client.py
packages/toolbox-core/src/toolbox_core/sync_client.py
packages/toolbox-core/src/toolbox_core/sync_tool.py
packages/toolbox-core/src/toolbox_core/tool.py
packages/toolbox-core/src/toolbox_core/utils.py

This PR enhances the type hints for `bound_params`, `auth_token_getters`, and `client_headers` arguments in the APIs of both tool and client classes.
Previously, these type hints incorrectly suggested that these callables could only be synchronous functions, or in some cases, specifically `Coroutine` objects:
* `auth_token_getters`: Expected `Callable[[], str]`
* `bound_params`: Expected `Callable[[], Any]`
* `client_headers`: `Coroutine`
This was inaccurate as these can also be asynchronous (`async def`) functions.
This PR corrects the type hints to accurately reflect that these callables can be either synchronous or asynchronous:
* **`auth_token_getter`**: Now accepts `Callable[[], str]` or `Callable[[], Awaitable[str]]`.
* **`bound_params`**: Now accepts `Callable[[], Any]` or …

chore: Improve type hints for async `bound_params`, `auth_token_getters`, and `client_headers`

---

packages/toolbox-core/src/toolbox_core/client.py
packages/toolbox-core/src/toolbox_core/sync_client.py
packages/toolbox-core/tests/conftest.py
packages/toolbox-core/tests/test_sync_client.py
packages/toolbox-langchain/src/toolbox_langchain/client.py

Fixes #208 
This change ensures that the `ToolboxClient` only closes client sessions that it creates and manages internally. If a client session is provided externally (i.e., injected into the `ToolboxClient`), the responsibility for managing its lifecycle, including closing it, remains with the entity that provided it. This prevents unintended closure of externally managed sessions.

fix(toolbox-core): Prevent `ToolboxClient` from closing externally managed client sessions

---

packages/toolbox-core/src/toolbox_core/client.py
packages/toolbox-core/src/toolbox_core/tool.py

Fixes #273 
Currently, the SDK client unconditionally attempts to parse all API responses as JSON. If the remote server returns an error (e.g., 403 Forbidden due to an authentication failure, or 404 Not Found), the response body is often HTML or plain text, not JSON.
This leads to a low-level `ContentTypeError`, which masks the original, more informative error from the server (like the HTTP status and reason). Users are left with a confusing `"response not parseable"` message instead of knowing the true cause of the failure.
This PR introduces a check to validate the HTTP response status before attempting to parse its body.
If the response status is not 200 OK, the client now captures the status code, reason phrase, and the raw response body.
It then raises a `RuntimeError` that includes …

docs: Improve API error handling for `toolbox-core` client

---

packages/toolbox-core/README.md
packages/toolbox-langchain/README.md
packages/toolbox-llamaindex/README.md

docs: Add complete e2e working quickstart link across all quickstart sections

---

packages/toolbox-llamaindex/README.md

This PR partially reverts some changes from #265, that seems to mistakenly remove the installation section and quickstart heading.

docs(toolbox-llamaindex): Partially reverts change to restore installation section

---

packages/toolbox-core/src/toolbox_core/auth_methods.py
packages/toolbox-core/src/toolbox_core/sync_client.py

This PR updates docstrings for the context manager functions `__enter__` and `__exit__` methods in sync client, and also on the auth module, to use the context manager while initializing the client.

docs(toolbox-core): Improve docstrings for context manager functions in sync client and auth module

---

packages/toolbox-llamaindex/README.md
packages/toolbox-llamaindex/src/toolbox_llamaindex/async_client.py
packages/toolbox-llamaindex/src/toolbox_llamaindex/client.py

Similar to [#308](https://github.com/googleapis/mcp-toolbox-sdk-python/pull/308)
This PR enhances `ToolboxClient` to support both synchronous and asynchronous context managers, improving its flexibility and ensuring proper resource management.
Users can now manage the client's lifecycle using either pattern:
```py
with ToolboxClient("...") as toolbox:
...
```
```py
async with ToolboxClient("...") as toolbox:
...
```
Additionally, a `close()` method has been added to automatically clean up underlying HTTP sessions when the client is garbage collected, preventing potential resource leaks.

feat(toolbox-llamaindex): Enable sync and async context management for ToolboxClient

---

packages/toolbox-core/tests/test_tool.py

This PR removes the redundant test [test_add_auth_token_getter_unused_token](https://github.com/Ganga4060/mcp-toolbox-sdk-python/blob/ffd8714c72497cf4ec01d0354d3eeb16ab48b9de/packages/toolbox-core/tests/test_tool.py#L476) from tests/test_tool.py.

chore: remove redundant unit test

---

packages/toolbox-core/src/toolbox_core/protocol.py
packages/toolbox-core/src/toolbox_core/tool.py
packages/toolbox-core/src/toolbox_core/utils.py
packages/toolbox-core/tests/test_client.py
packages/toolbox-core/tests/test_e2e.py
packages/toolbox-core/tests/test_protocol.py
packages/toolbox-core/tests/test_tool.py
packages/toolbox-core/tests/test_utils.py

Fixes https://github.com/googleapis/genai-toolbox/issues/1327
This PR refactors how `toolbox-core` handles tool parameter descriptions, moving them from dynamically generated docstrings directly into the function signature itself using `typing.Annotated`.
Previously, our approach involved using the `create_func_docstring` utility to dynamically build a Google-style `Args:` section within the ToolboxTool function's docstring. This method was unreliable and required custom logic just to format correctly (https://github.com/googleapis/mcp-toolbox-sdk-python/pull/369).
We found this approach to be extremely flaky, as it depended entirely on downstream orchestrators (like LangChain and LlamaIndex) to successfully parse that specific docstring format. This led to bugs, such as orchestrations …

fix(toolbox-core): Use typing.Annotated for reliable parameter descriptions instead of docstrings
